<?php

namespace Automas\Sales\Database\Seeders;

use Illuminate\Database\Seeder;
use Automas\Sales\Models\SalesAccount;
use Automas\Sales\Models\SalesAccountType;
use Automas\Sales\Models\SalesAccountIndustry;
use App\Models\User;

class DemoSalesAccountSeeder extends Seeder
{
    public function run($userId): void
    {
        if (SalesAccount::where('created_by', $userId)->exists()) {
            return;
        }

        $accountTypes = SalesAccountType::where('created_by', $userId)->pluck('id')->toArray();
        $accountIndustries = SalesAccountIndustry::where('created_by', $userId)->pluck('id')->toArray();
        $users = User::emp()->where('created_by', $userId)->pluck('id')->toArray();
        $users[] = $userId;

        if (empty($accountTypes) || empty($accountIndustries)) {
            return;
        }
        $accounts = [
            [
                'name' => 'TechCorp Solutions',
                'email' => 'contact@techcorp.com',
                'website' => 'www.techcorp.com',
                'billing_address' => '123 Business Park Drive',
                'billing_city' => 'San Francisco',
                'billing_state' => 'California',
                'billing_country' => 'United States',
                'billing_postal_code' => '94105',
                'shipping_address' => '123 Business Park Drive',
                'shipping_city' => 'San Francisco',
                'shipping_state' => 'California',
                'shipping_country' => 'United States',
                'shipping_postal_code' => '94105',
                'description' => 'Leading technology solutions provider specializing in enterprise software development and IT consulting services.',
                'is_active' => true,
            ],
            [
                'name' => 'Global Manufacturing Inc',
                'email' => 'sales@globalmanufacturing.com',
                'website' => 'www.globalmanufacturing.com',
                'billing_address' => '456 Industrial Boulevard',
                'billing_city' => 'Detroit',
                'billing_state' => 'Michigan',
                'billing_country' => 'United States',
                'billing_postal_code' => '48201',
                'shipping_address' => '789 Warehouse District',
                'shipping_city' => 'Detroit',
                'shipping_state' => 'Michigan',
                'shipping_country' => 'United States',
                'shipping_postal_code' => '48202',
                'description' => 'International manufacturing company producing automotive parts and industrial equipment for global markets.',
                'is_active' => true,
            ],
            [
                'name' => 'Healthcare Partners LLC',
                'email' => 'info@healthcarepartners.com',
                'website' => 'www.healthcarepartners.com',
                'billing_address' => '321 Medical Center Way',
                'billing_city' => 'Boston',
                'billing_state' => 'Massachusetts',
                'billing_country' => 'United States',
                'billing_postal_code' => '02101',
                'shipping_address' => '321 Medical Center Way',
                'shipping_city' => 'Boston',
                'shipping_state' => 'Massachusetts',
                'shipping_country' => 'United States',
                'shipping_postal_code' => '02101',
                'description' => 'Comprehensive healthcare services provider offering medical equipment and pharmaceutical solutions.',
                'is_active' => true,
            ],
            [
                'name' => 'Financial Services Group',
                'email' => 'contact@financialservices.com',
                'website' => 'www.financialservices.com',
                'billing_address' => '100 Wall Street',
                'billing_city' => 'New York',
                'billing_state' => 'New York',
                'billing_country' => 'United States',
                'billing_postal_code' => '10005',
                'shipping_address' => '100 Wall Street',
                'shipping_city' => 'New York',
                'shipping_state' => 'New York',
                'shipping_country' => 'United States',
                'shipping_postal_code' => '10005',
                'description' => 'Full-service financial institution providing banking, investment, and insurance solutions to corporate clients.',
                'is_active' => true,
            ],
            [
                'name' => 'Retail Chain Enterprises',
                'email' => 'procurement@retailchain.com',
                'website' => 'www.retailchain.com',
                'billing_address' => '555 Commerce Plaza',
                'billing_city' => 'Chicago',
                'billing_state' => 'Illinois',
                'billing_country' => 'United States',
                'billing_postal_code' => '60601',
                'shipping_address' => '777 Distribution Center',
                'shipping_city' => 'Chicago',
                'shipping_state' => 'Illinois',
                'shipping_country' => 'United States',
                'shipping_postal_code' => '60602',
                'description' => 'Major retail chain operating nationwide with focus on consumer electronics and home goods.',
                'is_active' => true,
            ],
            [
                'name' => 'Construction & Engineering Co',
                'email' => 'projects@construction-eng.com',
                'website' => 'www.construction-eng.com',
                'billing_address' => '888 Builder Avenue',
                'billing_city' => 'Houston',
                'billing_state' => 'Texas',
                'billing_country' => 'United States',
                'billing_postal_code' => '77001',
                'shipping_address' => '999 Project Site Road',
                'shipping_city' => 'Houston',
                'shipping_state' => 'Texas',
                'shipping_country' => 'United States',
                'shipping_postal_code' => '77002',
                'description' => 'Leading construction and engineering firm specializing in commercial and residential development projects.',
                'is_active' => false,
            ],
            [
                'name' => 'Green Energy Solutions',
                'email' => 'info@greenenergy.com',
                'website' => 'www.greenenergy.com',
                'billing_address' => '200 Solar Drive',
                'billing_city' => 'Phoenix',
                'billing_state' => 'Arizona',
                'billing_country' => 'United States',
                'billing_postal_code' => '85001',
                'shipping_address' => '200 Solar Drive',
                'shipping_city' => 'Phoenix',
                'shipping_state' => 'Arizona',
                'shipping_country' => 'United States',
                'shipping_postal_code' => '85001',
                'description' => 'Renewable energy company specializing in solar panel installation and wind energy solutions.',
                'is_active' => true,
            ],
            [
                'name' => 'Digital Marketing Agency',
                'email' => 'hello@digitalmarketing.com',
                'website' => 'www.digitalmarketing.com',
                'billing_address' => '150 Creative Boulevard',
                'billing_city' => 'Austin',
                'billing_state' => 'Texas',
                'billing_country' => 'United States',
                'billing_postal_code' => '73301',
                'shipping_address' => '150 Creative Boulevard',
                'shipping_city' => 'Austin',
                'shipping_state' => 'Texas',
                'shipping_country' => 'United States',
                'shipping_postal_code' => '73301',
                'description' => 'Full-service digital marketing agency providing SEO, social media, and online advertising solutions.',
                'is_active' => true,
            ],
            [
                'name' => 'Food & Beverage Corp',
                'email' => 'orders@foodbeverage.com',
                'website' => 'www.foodbeverage.com',
                'billing_address' => '300 Culinary Street',
                'billing_city' => 'Atlanta',
                'billing_state' => 'Georgia',
                'billing_country' => 'United States',
                'billing_postal_code' => '30301',
                'shipping_address' => '400 Distribution Way',
                'shipping_city' => 'Atlanta',
                'shipping_state' => 'Georgia',
                'shipping_country' => 'United States',
                'shipping_postal_code' => '30302',
                'description' => 'Leading food and beverage distributor serving restaurants and retail chains nationwide.',
                'is_active' => true,
            ],
            [
                'name' => 'Logistics & Transportation',
                'email' => 'dispatch@logistics.com',

                'website' => 'www.logistics.com',
                'billing_address' => '500 Highway Plaza',
                'billing_city' => 'Memphis',
                'billing_state' => 'Tennessee',
                'billing_country' => 'United States',
                'billing_postal_code' => '38101',
                'shipping_address' => '600 Freight Terminal',
                'shipping_city' => 'Memphis',
                'shipping_state' => 'Tennessee',
                'shipping_country' => 'United States',
                'shipping_postal_code' => '38102',
                'description' => 'Comprehensive logistics and transportation services including freight, warehousing, and supply chain management.',
                'is_active' => true,
            ],
            [
                'name' => 'Educational Services Inc',
                'email' => 'admin@educational.com',

                'website' => 'www.educational.com',
                'billing_address' => '700 Learning Lane',
                'billing_city' => 'Denver',
                'billing_state' => 'Colorado',
                'billing_country' => 'United States',
                'billing_postal_code' => '80201',
                'shipping_address' => '700 Learning Lane',
                'shipping_city' => 'Denver',
                'shipping_state' => 'Colorado',
                'shipping_country' => 'United States',
                'shipping_postal_code' => '80201',
                'description' => 'Educational technology and training services provider for schools and corporate learning programs.',
                'is_active' => true,
            ],
            [
                'name' => 'Real Estate Holdings',
                'email' => 'properties@realestate.com',

                'website' => 'www.realestate.com',
                'billing_address' => '800 Property Plaza',
                'billing_city' => 'Miami',
                'billing_state' => 'Florida',
                'billing_country' => 'United States',
                'billing_postal_code' => '33101',
                'shipping_address' => '800 Property Plaza',
                'shipping_city' => 'Miami',
                'shipping_state' => 'Florida',
                'shipping_country' => 'United States',
                'shipping_postal_code' => '33101',
                'description' => 'Commercial and residential real estate development and property management company.',
                'is_active' => true,
            ],
            [
                'name' => 'Pharmaceutical Research',
                'email' => 'research@pharma.com',

                'website' => 'www.pharma.com',
                'billing_address' => '900 Science Park',
                'billing_city' => 'San Diego',
                'billing_state' => 'California',
                'billing_country' => 'United States',
                'billing_postal_code' => '92101',
                'shipping_address' => '900 Science Park',
                'shipping_city' => 'San Diego',
                'shipping_state' => 'California',
                'shipping_country' => 'United States',
                'shipping_postal_code' => '92101',
                'description' => 'Pharmaceutical research and development company focused on innovative drug discovery and clinical trials.',
                'is_active' => false,
            ],
            [
                'name' => 'Automotive Parts Supply',
                'email' => 'sales@autoparts.com',

                'website' => 'www.autoparts.com',
                'billing_address' => '1000 Motor Avenue',
                'billing_city' => 'Cleveland',
                'billing_state' => 'Ohio',
                'billing_country' => 'United States',
                'billing_postal_code' => '44101',
                'shipping_address' => '1100 Warehouse Road',
                'shipping_city' => 'Cleveland',
                'shipping_state' => 'Ohio',
                'shipping_country' => 'United States',
                'shipping_postal_code' => '44102',
                'description' => 'Automotive parts supplier serving dealerships and repair shops with OEM and aftermarket components.',
                'is_active' => true,
            ],
            [
                'name' => 'Consulting & Advisory',
                'email' => 'contact@consulting.com',

                'website' => 'www.consulting.com',
                'billing_address' => '1200 Executive Suite',
                'billing_city' => 'Washington',
                'billing_state' => 'District of Columbia',
                'billing_country' => 'United States',
                'billing_postal_code' => '20001',
                'shipping_address' => '1200 Executive Suite',
                'shipping_city' => 'Washington',
                'shipping_state' => 'District of Columbia',
                'shipping_country' => 'United States',
                'shipping_postal_code' => '20001',
                'description' => 'Strategic business consulting firm providing management advisory and organizational development services.',
                'is_active' => true,
            ],
            [
                'name' => 'Entertainment Media Group',
                'email' => 'production@entertainment.com',

                'website' => 'www.entertainment.com',
                'billing_address' => '1300 Studio Boulevard',
                'billing_city' => 'Los Angeles',
                'billing_state' => 'California',
                'billing_country' => 'United States',
                'billing_postal_code' => '90001',
                'shipping_address' => '1300 Studio Boulevard',
                'shipping_city' => 'Los Angeles',
                'shipping_state' => 'California',
                'shipping_country' => 'United States',
                'shipping_postal_code' => '90001',
                'description' => 'Entertainment and media production company specializing in film, television, and digital content creation.',
                'is_active' => true,
            ],
            [
                'name' => 'Security Systems Ltd',
                'email' => 'security@systems.com',

                'website' => 'www.securitysystems.com',
                'billing_address' => '1400 Safety Street',
                'billing_city' => 'Las Vegas',
                'billing_state' => 'Nevada',
                'billing_country' => 'United States',
                'billing_postal_code' => '89101',
                'shipping_address' => '1500 Installation Center',
                'shipping_city' => 'Las Vegas',
                'shipping_state' => 'Nevada',
                'shipping_country' => 'United States',
                'shipping_postal_code' => '89102',
                'description' => 'Comprehensive security solutions provider offering surveillance systems, access control, and monitoring services.',
                'is_active' => true,
            ],
            [
                'name' => 'Textile Manufacturing',
                'email' => 'orders@textile.com',

                'website' => 'www.textile.com',
                'billing_address' => '1600 Fabric Mill Road',
                'billing_city' => 'Charlotte',
                'billing_state' => 'North Carolina',
                'billing_country' => 'United States',
                'billing_postal_code' => '28201',
                'shipping_address' => '1700 Distribution Hub',
                'shipping_city' => 'Charlotte',
                'shipping_state' => 'North Carolina',
                'shipping_country' => 'United States',
                'shipping_postal_code' => '28202',
                'description' => 'Textile manufacturing company producing fabrics and materials for fashion, home goods, and industrial applications.',
                'is_active' => false,
            ],
            [
                'name' => 'Cloud Computing Services',
                'email' => 'support@cloudcomputing.com',

                'website' => 'www.cloudcomputing.com',
                'billing_address' => '1800 Data Center Drive',
                'billing_city' => 'Seattle',
                'billing_state' => 'Washington',
                'billing_country' => 'United States',
                'billing_postal_code' => '98101',
                'shipping_address' => '1800 Data Center Drive',
                'shipping_city' => 'Seattle',
                'shipping_state' => 'Washington',
                'shipping_country' => 'United States',
                'shipping_postal_code' => '98101',
                'description' => 'Cloud infrastructure and computing services provider offering scalable solutions for enterprise clients.',
                'is_active' => true,
            ],
            [
                'name' => 'Aerospace Engineering',
                'email' => 'contracts@aerospace.com',

                'website' => 'www.aerospace.com',
                'billing_address' => '1900 Flight Path',
                'billing_city' => 'Huntsville',
                'billing_state' => 'Alabama',
                'billing_country' => 'United States',
                'billing_postal_code' => '35801',
                'shipping_address' => '1900 Flight Path',
                'shipping_city' => 'Huntsville',
                'shipping_state' => 'Alabama',
                'shipping_country' => 'United States',
                'shipping_postal_code' => '35801',
                'description' => 'Aerospace engineering and defense contractor specializing in satellite systems and aircraft components.',
                'is_active' => true,
            ],
            [
                'name' => 'Marine Transportation',
                'email' => 'shipping@marine.com',

                'website' => 'www.marine.com',
                'billing_address' => '2000 Harbor Drive',
                'billing_city' => 'Long Beach',
                'billing_state' => 'California',
                'billing_country' => 'United States',
                'billing_postal_code' => '90801',
                'shipping_address' => '2100 Port Terminal',
                'shipping_city' => 'Long Beach',
                'shipping_state' => 'California',
                'shipping_country' => 'United States',
                'shipping_postal_code' => '90802',
                'description' => 'International marine transportation and shipping services for cargo and container logistics.',
                'is_active' => true,
            ],
            [
                'name' => 'Biotechnology Research',
                'email' => 'lab@biotech.com',

                'website' => 'www.biotech.com',
                'billing_address' => '2200 Research Campus',
                'billing_city' => 'Cambridge',
                'billing_state' => 'Massachusetts',
                'billing_country' => 'United States',
                'billing_postal_code' => '02139',
                'shipping_address' => '2200 Research Campus',
                'shipping_city' => 'Cambridge',
                'shipping_state' => 'Massachusetts',
                'shipping_country' => 'United States',
                'shipping_postal_code' => '02139',
                'description' => 'Biotechnology research company developing innovative medical treatments and diagnostic solutions.',
                'is_active' => true,
            ],
            [
                'name' => 'Mining Operations Corp',
                'email' => 'operations@mining.com',

                'website' => 'www.mining.com',
                'billing_address' => '2300 Mineral Ridge',
                'billing_city' => 'Salt Lake City',
                'billing_state' => 'Utah',
                'billing_country' => 'United States',
                'billing_postal_code' => '84101',
                'shipping_address' => '2400 Processing Plant',
                'shipping_city' => 'Salt Lake City',
                'shipping_state' => 'Utah',
                'shipping_country' => 'United States',
                'shipping_postal_code' => '84102',
                'description' => 'Mining and mineral extraction company specializing in precious metals and industrial minerals.',
                'is_active' => false,
            ],
            [
                'name' => 'Telecommunications Network',
                'email' => 'network@telecom.com',

                'website' => 'www.telecom.com',
                'billing_address' => '2500 Communication Tower',
                'billing_city' => 'Dallas',
                'billing_state' => 'Texas',
                'billing_country' => 'United States',
                'billing_postal_code' => '75201',
                'shipping_address' => '2500 Communication Tower',
                'shipping_city' => 'Dallas',
                'shipping_state' => 'Texas',
                'shipping_country' => 'United States',
                'shipping_postal_code' => '75201',
                'description' => 'Telecommunications infrastructure provider offering network services and communication solutions.',
                'is_active' => true,
            ],
            [
                'name' => 'Sports Equipment Manufacturing',
                'email' => 'sales@sportsequip.com',

                'website' => 'www.sportsequip.com',
                'billing_address' => '2600 Athletic Avenue',
                'billing_city' => 'Portland',
                'billing_state' => 'Oregon',
                'billing_country' => 'United States',
                'billing_postal_code' => '97201',
                'shipping_address' => '2700 Distribution Center',
                'shipping_city' => 'Portland',
                'shipping_state' => 'Oregon',
                'shipping_country' => 'United States',
                'shipping_postal_code' => '97202',
                'description' => 'Sports equipment manufacturer producing gear for professional and recreational athletics.',
                'is_active' => true,
            ],
            [
                'name' => 'Chemical Processing Inc',
                'email' => 'safety@chemical.com',

                'website' => 'www.chemical.com',
                'billing_address' => '2800 Industrial Complex',
                'billing_city' => 'Baton Rouge',
                'billing_state' => 'Louisiana',
                'billing_country' => 'United States',
                'billing_postal_code' => '70801',
                'shipping_address' => '2900 Refinery Road',
                'shipping_city' => 'Baton Rouge',
                'shipping_state' => 'Louisiana',
                'shipping_country' => 'United States',
                'shipping_postal_code' => '70802',
                'description' => 'Chemical processing and manufacturing company producing industrial chemicals and specialty compounds.',
                'is_active' => true,
            ],
            [
                'name' => 'Renewable Energy Systems',
                'email' => 'projects@renewable.com',

                'website' => 'www.renewable.com',
                'billing_address' => '3000 Wind Farm Lane',
                'billing_city' => 'Amarillo',
                'billing_state' => 'Texas',
                'billing_country' => 'United States',
                'billing_postal_code' => '79101',
                'shipping_address' => '3000 Wind Farm Lane',
                'shipping_city' => 'Amarillo',
                'shipping_state' => 'Texas',
                'shipping_country' => 'United States',
                'shipping_postal_code' => '79101',
                'description' => 'Renewable energy systems developer specializing in wind and solar power generation projects.',
                'is_active' => true,
            ],
            [
                'name' => 'Publishing & Media House',
                'email' => 'editorial@publishing.com',

                'website' => 'www.publishing.com',
                'billing_address' => '3100 Press Boulevard',
                'billing_city' => 'New York',
                'billing_state' => 'New York',
                'billing_country' => 'United States',
                'billing_postal_code' => '10019',
                'shipping_address' => '3100 Press Boulevard',
                'shipping_city' => 'New York',
                'shipping_state' => 'New York',
                'shipping_country' => 'United States',
                'shipping_postal_code' => '10019',
                'description' => 'Publishing and media company producing books, magazines, and digital content for various markets.',
                'is_active' => false,
            ],
            [
                'name' => 'Insurance Solutions Group',
                'email' => 'claims@insurance.com',

                'website' => 'www.insurance.com',
                'billing_address' => '3200 Policy Plaza',
                'billing_city' => 'Hartford',
                'billing_state' => 'Connecticut',
                'billing_country' => 'United States',
                'billing_postal_code' => '06101',
                'shipping_address' => '3200 Policy Plaza',
                'shipping_city' => 'Hartford',
                'shipping_state' => 'Connecticut',
                'shipping_country' => 'United States',
                'shipping_postal_code' => '06101',
                'description' => 'Comprehensive insurance services provider offering commercial and personal insurance solutions.',
                'is_active' => true,
            ],
        ];

        foreach ($accounts as $accountData) {
            // Generate random country code and phone number
            $countryCodes = ['+1', '+44', '+33', '+49', '+34', '+61', '+81', '+86', '+91', '+55'];
            $countryCode = $countryCodes[array_rand($countryCodes)];
            $phone = $countryCode . mt_rand(1000000000, 9999999999);

            SalesAccount::create(array_merge($accountData, [
                'phone' => $phone,
                'assign_user_id' => !empty($users) ? $users[array_rand($users)] : null,
                'type_id' => !empty($accountTypes) ? $accountTypes[array_rand($accountTypes)] : null,
                'industry_id' => !empty($accountIndustries) ? $accountIndustries[array_rand($accountIndustries)] : null,
                'creator_id' => $userId,
                'created_by' => $userId,
            ]));
        }
    }
}
