<?php

namespace Automas\Sales\Database\Seeders;

use Illuminate\Database\Seeder;
use Automas\Sales\Models\SalesContact;
use Automas\Sales\Models\SalesAccount;
use App\Models\User;

class DemoSalesContactSeeder extends Seeder
{
    public function run($userId): void
    {
        if (SalesContact::where('created_by', $userId)->exists()) {
            return;
        }

        $accounts = SalesAccount::where('created_by', $userId)->get();
        $users = User::emp()->where('created_by', $userId)->pluck('id')->toArray();
        $users[] = $userId;
        
        if ($accounts->isEmpty()) {
            return;
        }
        
        $contacts = [
            [
                'name' => 'Robert Chen',
                'email' => 'robert.chen@techcorp.com',
                'job_title' => 'Chief Technology Officer',
                'department' => 'Technology',
                'lead_source' => 'Referral',
                'address' => '123 Business Park Drive',
                'city' => 'San Francisco',
                'state' => 'California',
                'postal_code' => '94105',
                'country' => 'United States',
                'description' => 'CTO responsible for technology strategy and innovation initiatives.',
                'preferred_contact_method' => 'Email',
            ],
            [
                'name' => 'Maria Rodriguez',
                'email' => 'maria.rodriguez@globalmanufacturing.com',
                'job_title' => 'Procurement Manager',
                'department' => 'Supply Chain',
                'lead_source' => 'Trade Show',
                'address' => '456 Industrial Boulevard',
                'city' => 'Detroit',
                'state' => 'Michigan',
                'postal_code' => '48201',
                'country' => 'United States',
                'description' => 'Manages supplier relationships and procurement processes.',
                'preferred_contact_method' => 'Phone',
            ],
            [
                'name' => 'Dr. James Wilson',
                'email' => 'james.wilson@healthcarepartners.com',
                'job_title' => 'Medical Director',
                'department' => 'Medical Operations',
                'lead_source' => 'Website',
                'address' => '321 Medical Center Way',
                'city' => 'Boston',
                'state' => 'Massachusetts',
                'postal_code' => '02101',
                'country' => 'United States',
                'description' => 'Senior physician overseeing medical operations and compliance.',
                'preferred_contact_method' => 'Email',
            ],
            [
                'name' => 'Jennifer Thompson',
                'email' => 'jennifer.thompson@financialservices.com',
                'job_title' => 'Chief Operating Officer',
                'department' => 'Operations',
                'lead_source' => 'Cold Call',
                'address' => '100 Wall Street',
                'city' => 'New York',
                'state' => 'New York',
                'postal_code' => '10005',
                'country' => 'United States',
                'description' => 'Oversees daily operations and strategic planning initiatives.',
                'preferred_contact_method' => 'Phone',
            ],
            [
                'name' => 'Michael Davis',
                'email' => 'michael.davis@retailchain.com',
                'job_title' => 'VP of Procurement',
                'department' => 'Purchasing',
                'lead_source' => 'Email Campaign',
                'address' => '555 Commerce Plaza',
                'city' => 'Chicago',
                'state' => 'Illinois',
                'postal_code' => '60601',
                'country' => 'United States',
                'description' => 'Leads procurement strategy and vendor management.',
                'preferred_contact_method' => 'Email',
            ],
            [
                'name' => 'Sarah Johnson',
                'email' => 'sarah.johnson@construction-eng.com',
                'job_title' => 'Project Manager',
                'department' => 'Engineering',
                'lead_source' => 'Referral',
                'address' => '888 Builder Avenue',
                'city' => 'Houston',
                'state' => 'Texas',
                'postal_code' => '77001',
                'country' => 'United States',
                'description' => 'Manages large-scale construction and engineering projects.',
                'preferred_contact_method' => 'Phone',
            ],
            [
                'name' => 'David Kim',
                'email' => 'david.kim@greenenergy.com',
                'job_title' => 'Business Development Director',
                'department' => 'Sales',
                'lead_source' => 'Social Media',
                'address' => '200 Solar Drive',
                'city' => 'Phoenix',
                'state' => 'Arizona',
                'postal_code' => '85001',
                'country' => 'United States',
                'description' => 'Drives business growth and partnership development.',
                'preferred_contact_method' => 'Email',
            ],
            [
                'name' => 'Lisa Anderson',
                'email' => 'lisa.anderson@digitalmarketing.com',
                'job_title' => 'Creative Director',
                'department' => 'Marketing',
                'lead_source' => 'Website',
                'address' => '150 Creative Boulevard',
                'city' => 'Austin',
                'state' => 'Texas',
                'postal_code' => '73301',
                'country' => 'United States',
                'description' => 'Leads creative strategy and campaign development.',
                'preferred_contact_method' => 'Email',
            ],
            [
                'name' => 'Thomas Brown',
                'email' => 'thomas.brown@foodbeverage.com',
                'job_title' => 'Operations Manager',
                'department' => 'Operations',
                'lead_source' => 'Trade Show',
                'address' => '300 Culinary Street',
                'city' => 'Atlanta',
                'state' => 'Georgia',
                'postal_code' => '30301',
                'country' => 'United States',
                'description' => 'Manages food distribution and supply chain operations.',
                'preferred_contact_method' => 'Phone',
            ],
            [
                'name' => 'Amanda White',
                'email' => 'amanda.white@logistics.com',
                'job_title' => 'Logistics Director',
                'department' => 'Logistics',
                'lead_source' => 'Referral',
                'address' => '500 Highway Plaza',
                'city' => 'Memphis',
                'state' => 'Tennessee',
                'postal_code' => '38101',
                'country' => 'United States',
                'description' => 'Oversees transportation and logistics operations.',
                'preferred_contact_method' => 'Phone',
            ],
            [
                'name' => 'Dr. Patricia Garcia',
                'email' => 'patricia.garcia@educational.com',
                'job_title' => 'Director of Technology',
                'department' => 'Education Technology',
                'lead_source' => 'Website',
                'address' => '700 Learning Lane',
                'city' => 'Denver',
                'state' => 'Colorado',
                'postal_code' => '80201',
                'country' => 'United States',
                'description' => 'Leads educational technology initiatives and training programs.',
                'preferred_contact_method' => 'Email',
            ],
            [
                'name' => 'Richard Martinez',
                'email' => 'richard.martinez@realestate.com',
                'job_title' => 'Property Manager',
                'department' => 'Real Estate',
                'lead_source' => 'Referral',
                'address' => '800 Property Plaza',
                'city' => 'Miami',
                'state' => 'Florida',
                'postal_code' => '33101',
                'country' => 'United States',
                'description' => 'Manages commercial and residential property portfolios.',
                'preferred_contact_method' => 'Phone',
            ],
            [
                'name' => 'Dr. Susan Lee',
                'email' => 'susan.lee@pharma.com',
                'job_title' => 'Research Director',
                'department' => 'Research & Development',
                'lead_source' => 'Trade Show',
                'address' => '900 Science Park',
                'city' => 'San Diego',
                'state' => 'California',
                'postal_code' => '92101',
                'country' => 'United States',
                'description' => 'Leads pharmaceutical research and clinical trial programs.',
                'preferred_contact_method' => 'Email',
            ],
            [
                'name' => 'Kevin Taylor',
                'email' => 'kevin.taylor@autoparts.com',
                'job_title' => 'Sales Manager',
                'department' => 'Sales',
                'lead_source' => 'Cold Call',
                'address' => '1000 Motor Avenue',
                'city' => 'Cleveland',
                'state' => 'Ohio',
                'postal_code' => '44101',
                'country' => 'United States',
                'description' => 'Manages automotive parts sales and dealer relationships.',
                'preferred_contact_method' => 'Phone',
            ],
            [
                'name' => 'Rachel Green',
                'email' => 'rachel.green@consulting.com',
                'job_title' => 'Senior Consultant',
                'department' => 'Consulting',
                'lead_source' => 'Referral',
                'address' => '1200 Executive Suite',
                'city' => 'Washington',
                'state' => 'District of Columbia',
                'postal_code' => '20001',
                'country' => 'United States',
                'description' => 'Provides strategic business consulting and organizational development.',
                'preferred_contact_method' => 'Email',
            ],
            [
                'name' => 'Mark Williams',
                'email' => 'mark.williams@entertainment.com',
                'job_title' => 'Production Manager',
                'department' => 'Production',
                'lead_source' => 'Social Media',
                'address' => '1300 Studio Boulevard',
                'city' => 'Los Angeles',
                'state' => 'California',
                'postal_code' => '90001',
                'country' => 'United States',
                'description' => 'Oversees film and television production projects.',
                'preferred_contact_method' => 'Email',
            ],
            [
                'name' => 'Nicole Adams',
                'email' => 'nicole.adams@securitysystems.com',
                'job_title' => 'Account Manager',
                'department' => 'Sales',
                'lead_source' => 'Website',
                'address' => '1400 Safety Street',
                'city' => 'Las Vegas',
                'state' => 'Nevada',
                'postal_code' => '89101',
                'country' => 'United States',
                'description' => 'Manages security system installations and client relationships.',
                'preferred_contact_method' => 'Phone',
            ],
            [
                'name' => 'Christopher Moore',
                'email' => 'christopher.moore@textile.com',
                'job_title' => 'Operations Director',
                'department' => 'Manufacturing',
                'lead_source' => 'Trade Show',
                'address' => '1600 Fabric Mill Road',
                'city' => 'Charlotte',
                'state' => 'North Carolina',
                'postal_code' => '28201',
                'country' => 'United States',
                'description' => 'Oversees textile manufacturing operations and quality control.',
                'preferred_contact_method' => 'Email',
            ],
            [
                'name' => 'Angela Clark',
                'email' => 'angela.clark@cloudcomputing.com',
                'job_title' => 'Solutions Architect',
                'department' => 'Technology',
                'lead_source' => 'Referral',
                'address' => '1800 Data Center Drive',
                'city' => 'Seattle',
                'state' => 'Washington',
                'postal_code' => '98101',
                'country' => 'United States',
                'description' => 'Designs and implements cloud infrastructure solutions for enterprise clients.',
                'preferred_contact_method' => 'Email',
            ],
            [
                'name' => 'Daniel Rodriguez',
                'email' => 'daniel.rodriguez@aerospace.com',
                'job_title' => 'Engineering Manager',
                'department' => 'Engineering',
                'lead_source' => 'Cold Call',
                'address' => '1900 Flight Path',
                'city' => 'Huntsville',
                'state' => 'Alabama',
                'postal_code' => '35801',
                'country' => 'United States',
                'description' => 'Manages aerospace engineering projects and defense contracts.',
                'preferred_contact_method' => 'Phone',
            ],
            [
                'name' => 'Emily Johnson',
                'email' => 'emily.johnson@marine.com',
                'job_title' => 'Operations Coordinator',
                'department' => 'Logistics',
                'lead_source' => 'Email Campaign',
                'address' => '2000 Harbor Drive',
                'city' => 'Long Beach',
                'state' => 'California',
                'postal_code' => '90801',
                'country' => 'United States',
                'description' => 'Coordinates marine transportation and shipping operations.',
                'preferred_contact_method' => 'Email',
            ],
            [
                'name' => 'Dr. Brian Wilson',
                'email' => 'brian.wilson@biotech.com',
                'job_title' => 'Chief Scientist',
                'department' => 'Research',
                'lead_source' => 'Website',
                'address' => '2200 Research Campus',
                'city' => 'Cambridge',
                'state' => 'Massachusetts',
                'postal_code' => '02139',
                'country' => 'United States',
                'description' => 'Leads biotechnology research and development initiatives.',
                'preferred_contact_method' => 'Email',
            ],
            [
                'name' => 'Steven Miller',
                'email' => 'steven.miller@mining.com',
                'job_title' => 'Site Manager',
                'department' => 'Operations',
                'lead_source' => 'Referral',
                'address' => '2300 Mineral Ridge',
                'city' => 'Salt Lake City',
                'state' => 'Utah',
                'postal_code' => '84101',
                'country' => 'United States',
                'description' => 'Oversees mining operations and mineral extraction processes.',
                'preferred_contact_method' => 'Phone',
            ],
            [
                'name' => 'Jessica Davis',
                'email' => 'jessica.davis@telecom.com',
                'job_title' => 'Network Manager',
                'department' => 'Infrastructure',
                'lead_source' => 'Trade Show',
                'address' => '2500 Communication Tower',
                'city' => 'Dallas',
                'state' => 'Texas',
                'postal_code' => '75201',
                'country' => 'United States',
                'description' => 'Manages telecommunications network infrastructure and services.',
                'preferred_contact_method' => 'Email',
            ],
            [
                'name' => 'Ryan Thompson',
                'email' => 'ryan.thompson@sportsequip.com',
                'job_title' => 'Product Manager',
                'department' => 'Product Development',
                'lead_source' => 'Social Media',
                'address' => '2600 Athletic Avenue',
                'city' => 'Portland',
                'state' => 'Oregon',
                'postal_code' => '97201',
                'country' => 'United States',
                'description' => 'Develops and markets sports equipment for professional athletes.',
                'preferred_contact_method' => 'Email',
            ],
            [
                'name' => 'Michelle Garcia',
                'email' => 'michelle.garcia@chemical.com',
                'job_title' => 'Safety Manager',
                'department' => 'Safety & Compliance',
                'lead_source' => 'Cold Call',
                'address' => '2800 Industrial Complex',
                'city' => 'Baton Rouge',
                'state' => 'Louisiana',
                'postal_code' => '70801',
                'country' => 'United States',
                'description' => 'Manages chemical processing operations and safety compliance.',
                'preferred_contact_method' => 'Phone',
            ],
            [
                'name' => 'Andrew Martinez',
                'email' => 'andrew.martinez@renewable.com',
                'job_title' => 'Project Director',
                'department' => 'Project Management',
                'lead_source' => 'Website',
                'address' => '3000 Wind Farm Lane',
                'city' => 'Amarillo',
                'state' => 'Texas',
                'postal_code' => '79101',
                'country' => 'United States',
                'description' => 'Develops renewable energy projects and sustainable solutions.',
                'preferred_contact_method' => 'Email',
            ],
            [
                'name' => 'Laura Anderson',
                'email' => 'laura.anderson@publishing.com',
                'job_title' => 'Editorial Director',
                'department' => 'Editorial',
                'lead_source' => 'Referral',
                'address' => '3100 Press Boulevard',
                'city' => 'New York',
                'state' => 'New York',
                'postal_code' => '10019',
                'country' => 'United States',
                'description' => 'Manages publishing operations and content development.',
                'preferred_contact_method' => 'Email',
            ],
            [
                'name' => 'Jonathan Lee',
                'email' => 'jonathan.lee@insurance.com',
                'job_title' => 'Insurance Advisor',
                'department' => 'Client Services',
                'lead_source' => 'Email Campaign',
                'address' => '3200 Policy Plaza',
                'city' => 'Hartford',
                'state' => 'Connecticut',
                'postal_code' => '06101',
                'country' => 'United States',
                'description' => 'Provides comprehensive insurance solutions and risk management services.',
                'preferred_contact_method' => 'Phone',
            ]
        ];

        foreach ($contacts as $contactData) {
            // Generate random country code and phone number
            $countryCodes = ['+1', '+44', '+33', '+49', '+34', '+61', '+81', '+86', '+91', '+55'];
            $countryCode = $countryCodes[array_rand($countryCodes)];
            $phone = $countryCode . mt_rand(1000000000, 9999999999);
            
            // Generate random tags
            $allTags = ['VIP', 'Decision Maker', 'Influencer', 'Technical', 'Finance'];
            $numTags = rand(1, 3);
            $selectedTags = array_rand(array_flip($allTags), $numTags);
            $tags = is_array($selectedTags) ? $selectedTags : [$selectedTags];
            
            // Generate social media URL
            $socialMedia = 'https://linkedin.com/in/' . strtolower(str_replace([' ', '.'], ['', ''], $contactData['name']));
            
            SalesContact::create(array_merge($contactData, [
                'phone' => $phone,
                'account_id' => $accounts->random()->id,
                'assign_user_id' => !empty($users) ? $users[array_rand($users)] : null,
                'is_active' => true,
                'creator_id' => $userId,
                'created_by' => $userId,
                'tags' => json_encode($tags),
                'social_media_urls' => $socialMedia,
            ]));
        }
    }
}